<?php

$Lang['ErrorInstall1']='It seems that you already have everything installed/updated so for security reasons access to this file is restricted!<br />Note that this file (<b>install.php</b>) should be deleted after succesfull install!';
//$Lang['ErrorInstall1']='Wygl±da na to, ¿e wszystko jest ju¿ zainstalowane/zaktualizowane, wiêc ze wzglêdów bezpieczeñstwa dostêp do tego pliku zosta³ zablokowany!<br />Zauwa¿, ¿e ten plik (<b>install.php</b>) powinien zostaæ usuniêty po poprawnej instalacji!';
$Lang['Install1']='Galaxy Forces Setup';
//$Lang['Install1']='Instalacja Galaxy Forces';
$Lang['Warning']='Warning';
//$Lang['Warning']='Ostrze¿enie';

$Lang['InstallationFinished']='Installation finished. You may want to visit your site now. If any errors occured you will need to correct them or start installation process again.<p />Remember that you will need to protect your configuration file and delete this script (<b>install.php</b>)!';
$Lang['WelcomePage']='Go to welcome page';
$Lang['Error']='Error';
$Lang['Error1']='Unknown database layer!';
$Lang['Error2']="Couldn't connect to database. Check your settings!";
$Lang['Error3a']="Couldn't create following table(s): ";
$Lang['Error3b']=". Remember that this setup don't remove any of existing tables. Maybe you need to drop some or change table prefix!";
$Lang['Error4']='Failed to create initial user!';
$Lang['Error5']='Configuration file could not be saved. You may wish to save it yourself. Here is the content of the file <b>include/config.php</b>:';
$Lang['Error6']='Failed SQL queries: ';
$Lang['WarningInstall1']='Configuration file <b>include/config.php</b> does not exists or is not writeable! In this case you will have to save autogenerated configuration file and you put this file yourself. If you have shell access you can create this file and change its permissions using this command: <p /><code>touch include/config.php && chmod 666 include/config.php</code>';
$Lang['WarningInstall2']="Log directory <b>log/</b> is not writeable! You need this or you will not be able to update in future. You can do this by the following command: <p><code>chmod 777 log</code></p>Or if you don't want to set global permission to whole directory you should create and set the permissions for three files: <b>log/common.log</b> (write), <b>log/chat.log</b> (write), <b>log/VERSION.txt</b> (read/write) what you can do by typing:<p /><code>touch log/common.log && chmod 622 log/common.log<br />touch log/chat.log && chmod 666 log/chat.log<br />touch log/VERSION.txt && chmod 666 log/VERSION.txt</code>";
$Lang['Install']='Install';
$Lang['Update']='Update';
$Lang['InstallMode']='Installation mode';
$Lang['DatabaseType']='Database type';
$Lang['DatabaseHost']='Host';
$Lang['DatabaseUser']='Database user';
$Lang['DatabasePass']='Password';
$Lang['DatabaseName']='Database name';
$Lang['DatabasePrefix']='Table prefix (must *NOT* contain spaces)';
$Lang['DatabaseCreate']='Create database (user must have enough rights)';
$Lang['InitialCreate']='Create initial user (recommended)';
$Lang['CreateWorld']='Create world';
$Lang['CreateItems']='Create items';
$Lang['CreateTables']='Create required tables';
$Lang['DatabaseSettings']='Database settings';
$Lang['InitialSettings']='Initialization stuff';
$Lang['Install default .htaccess file']='';
